### ISSUE TITLE
Document how to create secrets for github actions

### ISSUE THREAD

**Issue by tim-schilling** [django-commons/controls#22]
I'm not sure how to generate the `TERRAFORM_MANAGEMENT_GITHUB_TOKEN` or what needs to be granted. We should get that documented.

**Comment by cunla** [comment]
terraform works with new fine-grained personal access tokens only.

I intentionally left the old token so we can compare permissions:
New token: https://github.com/organizations/django-commons/settings/personal-access-tokens/345692
Old token: https://github.com/organizations/django-commons/settings/personal-access-tokens/328567

==> I suspect it is write permission on `attestations api`, but did not have a chance to try.

Once you generate the PAT, set it up as a value on the organization secret `TERRAFORM_MANAGEMENT_GITHUB_TOKEN`.
