### ISSUE TITLE
Branch protection automation via terraform

### ISSUE THREAD

**Issue by cunla** [django-commons/controls#30]
Should we enable branch protection setting via the `repositories.tfvars`? Currently there is a placeholder for it `enable_branch_protection` but it doesn't do much.

We can have for repository these settings:
```
repo { 
    enable_branch_protection = optional(bool, true)
    required_status_checks_contexts = optional(list(string), [])
    required_pr_approvals = 2
}
```
and then use the commented tf-code here: https://github.com/django-commons/controls/blob/main/terraform/resources-repos.tf#L49-L76

**Comment by tim-schilling** [comment]
I don't think we want to enable this by default. I think it'd be a good think to recommend/suggest, but it's not something we should dictate.

We're not here to tell people how to maintain a library. If we were going to be doing actual maintenence, then that would change.
