### ISSUE TITLE
GitHub action - New member action fails to apply terraform plan

### ISSUE THREAD

**Issue by tim-schilling** [django-commons/controls#64]
When a new member is added via the "New member" action on the membership repo, it creates a PR to update the terraform org vars. When this PR is merged, the apply terraform action fails because the plan didn't exist as a comment on the PR.

The plan typically gets added as a comment from a GHA workflow. However, since this PR is created by a GHA, it doesn't trigger subsequent actions. There are workaround identified here.

I think we have two choices:

1. Implement one of the workarounds above (I lean towards the GitHub App token option)
2. Allow these PRs to avoid the terraform plan requirement

I lean towards 1 being the better option.

**Comment by tim-schilling** [comment]
This can be worked around without a code change by closing the PR and re-opening. See https://github.com/django-commons/membership/pull/103

**Comment by ryancheley** [comment]
@tim-schilling I didn't have any issues when adding leogregianin in https://github.com/django-commons/membership/pull/105. Does that mean that I missed a step, or that this doesn't happen with each member addition? 🤔

**Comment by tim-schilling** [comment]
@ryancheley did you use the github action?

**Comment by tim-schilling** [comment]
https://github.com/django-commons/membership/actions/workflows/add_member.yml

**Comment by ryancheley** [comment]
@tim-schilling ugh … no, I missed that part 🤦  … I just made the update directly to the `tfvars` file.

**Comment by cunla** [comment]
Done, note the PAT used is under my user, hence the PRs will be created under my user.

Also, when a new `New member` issue is opened - the PR should be created automatically now.

**Comment by tim-schilling** [comment]
Thanks @cunla!

**Comment by Stormheg** [comment]
Nice work Daniel!
